apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: wg-easy
  labels:
    app: wg-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      initContainers:
        - name: sysctl-init
          image: busybox
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1; sysctl -w net.ipv4.conf.all.src_valid_mark=1
          securityContext:
            privileged: true
      containers:
        - name: wg-easy
          image: weejewel/wg-easy
          envFrom:
            - configMapRef:
                name: wg-easy-config
          ports:
            - name: wg-ui
              containerPort: 51821
              protocol: TCP
            - name: wg-vpn
              containerPort: 51820
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - name: wg-config
              mountPath: /etc/wireguard
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wg-easy-pvc
