apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-main
  namespace: headscale
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-path
  resources:
    requests:
      storage: "1Gi"
